# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=---testeeee

-----testeeee
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
-----testeeee--

###

# @name create-transcription
POST http://localhost:3333/videos/fb201272-de9b-435b-bb61-dd62ef5617e9/transcription
Content-Type: application/json

{
  "prompt": "summoners war, viewership"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "fb201272-de9b-435b-bb61-dd62ef5617e9",
  "temperature": 0.5,
  "template": "Generate an abstract from the video transcription: '''{transcription}'''"
}